name: maseradb-spark

services:
  spark-master:
    container_name: maseradb-spark-master
    build: .
    image: maseradb-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - ./logs:/opt/spark/spark-events
      - ./wallet:/opt/wallet
    env_file:
      - .env.spark
    ports:
      - '9091:8080'
      - '7077:7077'
    networks:
      - data-cluster

  spark-history-server:
    container_name: maseradb-spark-history
    image: maseradb-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./logs:/opt/spark/spark-events
    ports:
      - '18081:18080'
    networks:
      - data-cluster

  worker:
    image: maseradb-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - ./logs:/opt/spark/spark-events
      - ./wallet:/opt/wallet
    networks:
      - data-cluster
networks:
  data-cluster:
    external: true
